In [39]:
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.keys import Keys

import time
import pandas as pd

In [40]:
service = Service(ChromeDriverManager().install())
driver = webdriver.Chrome(service=service)
driver.maximize_window()
url = 'https://t.ly/3gJ4W'
driver.get(url)
time.sleep(3) # สร้าง delay 3 วิ

In [41]:
df = pd.read_excel('data.xlsx')
df

          Full name           Email  Mobile number University/Organization
0         Steve Vai  sv@example.com      980000001                 9expert
1        Gary Moore  gm@example.com      980000002                 9expert
2      Joe Satriani  js@example.com      980000003                 9expert
3      Eric Clapton  ec@example.com      980000004                 9expert
4      Jimi Hendrix  jh@example.com      980000005                 9expert
5        Jimmy Page  jp@example.com      980000006                 9expert
6             Slash   s@example.com      980000007                 9expert
7  Yngwie Malmsteen  ym@example.com      980000008                 9expert
8    Carlos Santana  cs@example.com      980000009                 9expert

In [42]:
for i in df.index:
    full_name_field = driver.find_element('xpath', '//*[@id="mG61Hd"]/div[2]/div/div[2]/div[1]/div/div/div[2]/div/div[1]/div/div[1]/input')
    full_name_field.send_keys(df['Full name'][i]) # (df['Full name'][i]) คือการทำ loop df จาก code ด้านบน

    email_field = driver.find_element('xpath', '//*[@id="mG61Hd"]/div[2]/div/div[2]/div[2]/div/div/div[2]/div/div[1]/div/div[1]/input')
    email_field.send_keys(df['Email'][i])

    mobile_number_field = driver.find_element('xpath', '//*[@id="mG61Hd"]/div[2]/div/div[2]/div[3]/div/div/div[2]/div/div[1]/div/div[1]/input')
    mobile_number_field.send_keys('0'+str(df['Mobile number'][i])) #ใส่เลขตรงๆไม่ได้ ต้องแปลง type เป็น str

    university_field = driver.find_element('xpath', '//*[@id="mG61Hd"]/div[2]/div/div[2]/div[4]/div/div/div[2]/div/div[1]/div/div[1]/input')
    university_field.send_keys(df['University/Organization'][i])

    submit_button = driver.find_element('xpath', '//*[@id="mG61Hd"]/div[2]/div/div[3]/div[1]/div[1]/div/span/span')
    submit_button.click()
    driver.back()